export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
export const VALIDATE = 'VALIDATE'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const UPLOAD_AVATAR = 'UPLOAD_AVATAR'
